name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main
      - backend
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend.yml"
  workflow_dispatch:

jobs:
  prod:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "codama-476202"
          workload_identity_provider: "projects/848683614417/locations/global/workloadIdentityPools/default/providers/github"
          token_format: "access_token"
          service_account: "default@codama-476202.iam.gserviceaccount.com"
      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
          registry: "asia-northeast1-docker.pkg.dev"
      - name: Build, tag and push container
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: "backend/"
          push: true
          tags: |
            asia-northeast1-docker.pkg.dev/codama-476202/codama/backend:${{ github.sha }}
            asia-northeast1-docker.pkg.dev/codama-476202/codama/backend:latest
      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: "default"
          region: "asia-northeast1"
          image: "asia-northeast1-docker.pkg.dev/codama-476202/codama/backend:latest"
